### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by jiangzhengwenjz** [jiangzhengwenjz/totkol#1]
- [x] Confirm the compiler: agbcc or old_agbcc? 
- [x] Match libraries
- [ ] Decompile and document used gba libraries
- [ ] Use information from https://gamefaqs.gamespot.com/gba/468482-tactics-ogre-the-knight-of-lodis/faqs/17186 and https://gamefaqs.gamespot.com/gba/468482-tactics-ogre-the-knight-of-lodis/faqs/17074 (constants, structs, charmap, etc. )
